ervices:
- docker
script:
- export SAVE=$PWD cnt="ubusqlctr" slim=".slim"
- docker build -t ${cnt} .
- >
  sudo ./docker-slim build 
  --mount ${SAVE}/scripts:/scripts
  --entrypoint /scripts/testsql.sh
  --include-path /entry.sh
  --include-path /bin/mkdir 
  --include-path /bin/touch 
  --include-path /bin/chmod 
  --include-path /bin/ls
  --include-path /bin/echo
  --include-path /bin/sleep
  --include-path /usr/lib/mysql
  --continue-after 10
  --mount /var/lib/mysql:/var/lib/mysql 
  --http-probe 
  ${cnt} 
  
before_deploy:
- cd
- wget `curl -s https://api.github.com/repos/appc/docker2aci/releases | grep browser_download_url | head -n 1 | cut -d '"' -f 4` -O d2a.tar.gz
- tar -zxf d2a.tar.gz && rm d2a.tar.gz && d2a=`ls | grep "docker2aci*"` && d2a=`basename  $d2a` && alias d2a='${PWD}/${d2a}/docker2aci'
- docker save -o ${cnt}.slim.tar ${cnt}.slim
- "${PWD}/${d2a}/docker2aci ${cnt}.slim.tar"
- xz -9 -c ${cnt}.slim.tar > ${cnt}.slim.tar.xz
- docker login -e $QUAYE -u $QUAYL -p $QUAYP  quay.io
- docker tag ${cnt}${slim} quay.io/natostanco/$cnt:$TRAVIS_TAG
- docker push quay.io/natostanco/$cnt:$TRAVIS_TAG
deploy:
  provider: releases
  api_key:
    secure: qdwzSqdO3vzl0jZFnB6tpHdTnC10dhex+9Z2kdyc3quO5MpnMjqPhpPcTyDBoO01XuSVsIgCk8am3wzKxofIrheaERaeF8adFtbbk7jVkQHt+JELIisicd+kr1RxqtRMSfvvJ4fffjsp9OYAiMKkpfwhKDoWjZTCpG6nMnmMrVAWrMSMfEKxy5MxQZdAX0JpH/2cE22Qp8vHmynlAJySvtHDfDCFBvKzWxWTfixkh+WPqf045huSl3ejNoYlGvfpB43uwOlU2bQbdiwfuZld8aYQ9NaaoVFO4Q3yPfkAWiwsBXgL+t1+GWezPnTxUdvMNdk0N+mRdgvKRtZCy5rXvUMe5H9QbBJYicwQt2oJoSi+5p/uL6VNnjreg8GIgt5ndgo8ah5oHxLn94Cg/KboCbFw0/vheJD8JB63kDc09RG1eBgY1HYN1smrZoAjTx70n+le+RXorH7xVZO01Wu6dGOKjw65M/IYpa1+tgjl55kRlJEyRWyGq412Xq+WXlsqB8oBOs+TR15sQaB8xjYQ6kCpefejdlg0juwLJda/0E/gaPPkIpLTahRcop7S+oeLZiLC7zcS+uPGe+p7ow2k0pRZe25Z7EHb5OVBPAOaweWtCZiRNTioib0D3moo1UEkEGUTjWpDlBToUtFSPY//5vxHkBfN2fizLH+pKw3/Atc=
  file:
  - "${cnt}.slim.tar.xz"
  - "${cnt}.slim-latest.aci"
  skip_cleanup: true
  on:
    tags: true
